on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy this Acid project.
    steps:
      - uses: actions/checkout@v3
      - id: build
        name: Site compilation.
        run: wget https://blckunicorn.art/assets/scripts/acid.sh && bash acid.sh . && ls
        shell: bash
      - name: Site deployment.
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
