on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy this Acid project.
    steps:
      - uses: actions/checkout@v3
      - id: build
        run: wget https://blckunicorn.art/assets/scripts/acid.sh && bash acid.sh . && ls
        shell: bash
